version: 2
updates:
# MASTER branch
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    assignees:
      - "RomiC"
    commit-message:
      prefix: "🆙 🛠️"
    directory: "/"
    labels:
      - "dependencies"
      - "dx"
    open-pull-requests-limit: 10
    reviewers:
      - "RomiC"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    assignees:
      - "RomiC"
    commit-message:
      prefix: "🆙 📦"
    directory: "/"
    labels:
      - "dependencies"
      - "dx"
    open-pull-requests-limit: 10
    reviewers:
      - "RomiC"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3
    versioning-strategy: increase

# V3.X branch
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    assignees:
      - "RomiC"
    commit-message:
      prefix: "🆙 🛠️"
    directory: "/"
    labels:
      - "dependencies"
      - "dx"
      - "v3.x"
    open-pull-requests-limit: 10
    reviewers:
      - "RomiC"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3
    target-branch: "v3.x"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    assignees:
      - "RomiC"
    commit-message:
      prefix: "🆙 📦"
    directory: "/"
    labels:
      - "dependencies"
      - "dx"
      - "v3.x"
    open-pull-requests-limit: 10
    reviewers:
      - "RomiC"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3
    target-branch: "v3.x"
    versioning-strategy: increase
