name: Tests

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - v4.x

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["22", "24"]
    name: Test with node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm run test:coverage
      - uses: coverallsapp/github-action@v2.3.8
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: node v${{ matrix.node }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    name: Publishing coverage report
    steps:
      - uses: coverallsapp/github-action@v2.3.8
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
